server:
  port: 8083
spring:
  application:
    name: notification-service
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      properties:
        spring.json.type.mapping: event:com.example.notificationservice.OrderPlacedEvent
      group-id: notificationId
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

