server:
  port: 8082
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5434/order
    username: order
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

