#todo:config server
spring:
  datasource:
    url: jdbc:postgresql://product-db:5433/product
  kafka:
    producer:
      bootstrap-servers: kafka:29092
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

