server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active:
      - git
  cloud:
    config:
      server:
        git:
#         your link to github repository with configs
          uri: https://github.com/aviNelson/config.git
          password:
#         your access token to the github repository with configs
          username: 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
